version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: ex_doc
    versions:
    - 0.23.0
    - 0.24.0
    - 0.24.1
  - dependency-name: timex
    versions:
    - 3.6.3
    - 3.6.4
    - 3.7.1
    - 3.7.3
  - dependency-name: credo
    versions:
    - 1.5.4
